
package Views;

import Controlers.Controlador;
import Models.ListaDoble;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Limbo
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    ListaDoble<Integer> lista1;
    ListaDoble<Integer> lista2;
    Controlador controlador;
    public FramePrincipal() {
        lista1 = new ListaDoble<Integer>();
        lista2 = new ListaDoble<Integer>();
        controlador = new Controlador();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        primerLista = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        segundalLista = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        sumarButton = new javax.swing.JButton();
        restarButton = new javax.swing.JButton();
        multiplicarButton = new javax.swing.JButton();
        dividirButton = new javax.swing.JButton();
        calcularYGuardar = new javax.swing.JButton();
        importFile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaResultados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SuperCalculadora");

        primerLista.setColumns(20);
        primerLista.setRows(5);
        jScrollPane1.setViewportView(primerLista);

        jLabel2.setText("Primer digito");

        segundalLista.setColumns(20);
        segundalLista.setRows(5);
        jScrollPane2.setViewportView(segundalLista);

        jLabel3.setText("Segundo digito");

        sumarButton.setText("Sumar");
        sumarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarButtonActionPerformed(evt);
            }
        });

        restarButton.setText("Restar");
        restarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarButtonActionPerformed(evt);
            }
        });

        multiplicarButton.setText("Multiplicar");
        multiplicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarButtonActionPerformed(evt);
            }
        });

        dividirButton.setText("Dividir");
        dividirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirButtonActionPerformed(evt);
            }
        });

        calcularYGuardar.setText("Calcular Todos y guardar");
        calcularYGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularYGuardarActionPerformed(evt);
            }
        });

        importFile.setText("Reconocer desde archivo");
        importFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFileActionPerformed(evt);
            }
        });

        areaResultados.setColumns(20);
        areaResultados.setRows(5);
        jScrollPane3.setViewportView(areaResultados);

        jLabel4.setText("Registro de procesos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(multiplicarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dividirButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(importFile))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sumarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calcularYGuardar)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicarButton)
                    .addComponent(dividirButton)
                    .addComponent(importFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumarButton)
                    .addComponent(restarButton)
                    .addComponent(calcularYGuardar))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void importFileActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File file = fileChooser.getSelectedFile();
        if(file != null){
            ArrayList<String> listas = controlador.obtenerStringsDesdeArchivo(file);
            if(listas.size() > 1 && Pattern.matches("[0-9]+", listas.get(0).toString()) && Pattern.matches("[0-9]+", listas.get(1).toString())){
                primerLista.setText(listas.get(0));
                segundalLista.setText(listas.get(1));
            } else {
                JOptionPane.showMessageDialog(null, "existe un problema con su archivo");
            }
        } else {
        }
    }                                          

    private void calcularYGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        ListaDoble<Integer> lista1 = controlador.separarElementosEnLista(primerLista.getText());
        ListaDoble<Integer> lista2 = controlador.separarElementosEnLista(segundalLista.getText());
        
        String mayor = controlador.getGreaterList(lista1, lista2);
        String suma = controlador.sumarListas(lista1, lista2);
        String resta = controlador.restarListas(lista1, lista2);
        String multiplicacion = controlador.multiplicarListas(lista1, lista2);
        String[] division = controlador.dividirListas(lista1, lista2);
        
        String[] resultado = {mayor, suma, resta, multiplicacion, division[0] , division[1]};
        areaResultados.setText("");
        for (String string : resultado) {
			areaResultados.setText(areaResultados.getText() + string + "\n");
		}
        controlador.crearArchivo(resultado);
    }                                                

    private void multiplicarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        ListaDoble<Integer> lista1 = controlador.separarElementosEnLista(primerLista.getText());
        ListaDoble<Integer> lista2 = controlador.separarElementosEnLista(segundalLista.getText());
        String producto = controlador.multiplicarListas(lista1, lista2);
        areaResultados.setText(producto);
    }                                                 

    private void dividirButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        ListaDoble<Integer> lista1 = controlador.separarElementosEnLista(primerLista.getText());
        ListaDoble<Integer> lista2 = controlador.separarElementosEnLista(segundalLista.getText());
        String[] producto = controlador.dividirListas(lista1, lista2);
        areaResultados.setText(producto[0] + "\n" + producto[1]);
    }                                             

    private void sumarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        ListaDoble<Integer> lista1 = controlador.separarElementosEnLista(primerLista.getText());
        ListaDoble<Integer> lista2 = controlador.separarElementosEnLista(segundalLista.getText());
        String producto = controlador.sumarListas(lista1, lista2);
        areaResultados.setText(producto);
    }                                           

    private void restarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        ListaDoble<Integer> lista1 = controlador.separarElementosEnLista(primerLista.getText());
        ListaDoble<Integer> lista2 = controlador.separarElementosEnLista(segundalLista.getText());
        String producto = controlador.restarListas(lista1, lista2);
        areaResultados.setText(producto);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton calcularYGuardar;
    private javax.swing.JButton dividirButton;
    private javax.swing.JButton importFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea areaResultados;
    private javax.swing.JButton multiplicarButton;
    private javax.swing.JTextArea primerLista;
    private javax.swing.JButton restarButton;
    private javax.swing.JTextArea segundalLista;
    private javax.swing.JButton sumarButton;
    // End of variables declaration                   
}
